--- 
services: 
  api: 
    build: 
      context: "."
      dockerfile: PaymentGatewayApi/Dockerfile
    depends_on: 
      - db
    ports: 
      - "8080:80"
  db: 
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Ax+themA
    image: mcr.microsoft.com/mssql/server
    ports: 
      - "1434:1433"
  web: 
    build: 
      context: "."
      dockerfile: MerchantAdmin/Dockerfile
    depends_on: 
      - db
    ports: 
      - "8000:80"
version: "3"
